// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBusXcGjRWUjDoe-eM4JVprgf2IRJz3Ngw',
    appId: '1:913778015345:web:e3bce0e15e03480e1aafd0',
    messagingSenderId: '913778015345',
    projectId: 'gen-lang-client-0718451481',
    authDomain: 'gen-lang-client-0718451481.firebaseapp.com',
    storageBucket: 'gen-lang-client-0718451481.firebasestorage.app',
    measurementId: 'G-S831RKGG76',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxqYEVJmoB_L8Mxem6dfoAO_SZweOM4ow',
    appId: '1:913778015345:android:a4af7a75000a992b1aafd0',
    messagingSenderId: '913778015345',
    projectId: 'gen-lang-client-0718451481',
    storageBucket: 'gen-lang-client-0718451481.firebasestorage.app',
  );
}
